name: Terraform CI/CD

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Init Terraform
      - name: Terraform Init
        run: |
          cd env/prod
          terraform init -backend-config="key=env/prod/terraform.tfstate"

      # Validate syntax
      - name: Terraform Validate
        run: |
          cd env/prod      
          terraform validate

      # Plan changes
      - name: Terraform Plan
        run: |
          cd env/prod
          terraform plan -out=tfplan

      # Auto-apply changes (careful!)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd env/prod
          terraform apply -auto-approve tfplan
